const querySubjects: string[] = [
  "Change of Status from Minor to Major",
  "Claim for Dividends",
  "Claim for Shares",
  "Clarification Reg Buy Back of Securities",
  "Clarification regarding Shares",
  "Clarification regarding Warrant (s)",
  "Complaint relating to Transfer of Shares",
  "Correction of Bank Mandate",
  "Correction/Revalidation of Fractional Entitlement",
  "Demat of Shares",
  "Deletion/Transmission of Shares",
  "Duplicate issues of Shares",
  "Excess/Short Payment of Dividend",
  "General Queries regarding First Call",
  "Letter Request to Change/Correction/Addition of Name",
  "Letter Request to Fractional Shares",
  "Loss of Securities and request for Issue of Duplicate",
  "Non Receipt of Annual Report",
  "Non Receipt of Call Notice",
  "Non Receipt of Dividend Warrants",
  "Non Receipt of Fresh/New Securities",
  "Non Receipt of Securities",
  "Non Receipt of TAX Deduction Certificate (TDS)",
  "Queries regarding TAX Deduction Certificate",
  "Regarding TAX Deduction Certificate-Complaint",
  "Refund of TDS",
  "Request for Transmission of Securities",
  "Request for Transmission of Securities – TRF",
  "Request for Transposition of Names on Securities",
  "Transfer of Shares",
  "Updation of Telephone/FAX/Mobile/Email/AAdhar",
  "Others"
];

export default querySubjects;
